version: '3.9'

services:
  postgres:
    image: postgres:16
    restart: always
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: room-booking
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: